name: Build and test
on:
  push:
    branches:
      - actions
jobs:
  standalone:
    strategy:
      matrix:
        include:
          - os: ubuntu-16.04
            deps: 'cmake libnlopt-dev'
          - os: ubuntu-18.04
            deps: 'cmake libnlopt-dev'
          - os: ubuntu-20.04
            deps: 'cmake libnlopt-cxx-dev'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install ${{ matrix.deps }}
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make
      - name: Run tests
        run: |
          cd build
          ctest --extra-verbose --output-on-failure
  ros:
    runs-on: ubuntu-latest
    container:
      image: ros:noetic-ros-core
    steps:
      - run: rosversion --distro