name: Build and test
on:
  push:
    branches:
      - actions
jobs:
  standalone:
    strategy:
      matrix:
        include:
          - os: ubuntu-16.04
            deps: 'cmake libnlopt-dev'
          - os: ubuntu-18.04
            deps: 'cmake libnlopt-dev'
          - os: ubuntu-20.04
            deps: 'cmake libnlopt-cxx-dev'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install ${{ matrix.deps }}
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make
      - name: Run tests
        run: |
          cd build
          ctest --extra-verbose --output-on-failure
  ros:
    strategy:
      matrix:
        rosdistro: [kinetic, melodic, noetic]
    runs-on: ubuntu-latest
    container:
      image: ros:${{ matrix.rosdistro }}-ros-base
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
        with:
          path: src/nlopt11
      - name: Run rosdep-install
        run: |
          source /opt/ros/${{ matrix.rosdistro }}/setup.bash
          sudo apt update
          rosdep update
          rosdep --version
          sudo rosdep install --from-paths src --ignore-src --default-yes -r
      - name: Build
        run: |
          source /opt/ros/${{ matrix.rosdistro }}/setup.bash
          catkin_make
      - name: Run tests
        run: |
          source /opt/ros/${{ matrix.rosdistro }}/setup.bash
          catkin_make run_tests